### ISSUE TITLE
Mistake with sharing posts

### ISSUE THREAD

**Issue by rsipakov** [timlrx/tailwind-nextjs-starter-blog#102]
I discovered a possible mistake with sharing posts. If you copy and paste the post link, there is no error. But if you try to share a post from a mobile device, then two pictures are substituted. 

The example is on the screenshot for the post: https://www.timlrx.com/blog/growth-hacking-github-how-to-get-github-stars

The first variant where the copied link was used. The second variant where the post was shared on mobile devices (iPhone).

<img width="650" alt="Screen Shot 2021-07-03 at 2 55 00 AM" src="https://user-images.githubusercontent.com/34224178/124346039-8f4c5600-dbaa-11eb-9712-72e55604a98d.png">

**Comment by timlrx** [comment]
That's probably due to the way `next-seo` is injected in the original version of the template which I am using which duplicates the header. It should have been fixed in v1 branch of the template.

I don't have an iPhone to check, but can you verify that you get the same problem in the [current version of the introductory post](https://tailwind-nextjs-starter-blog.vercel.app/blog/introducing-tailwind-nextjs-starter-blog) and let me know if the [v1 development version](https://tailwind-nextjs-starter-blog-l15iqhdbd-timlrx.vercel.app/blog/introducing-tailwind-nextjs-starter-blog) is fine? Thanks!

**Comment by rsipakov** [comment]
Two images are present when using both links.

<img width="637" alt="Screen Shot 2021-07-06 at 11 24 58 PM" src="https://user-images.githubusercontent.com/34224178/124695680-abedd400-deb1-11eb-91aa-d82b300ff691.png">

**Comment by timlrx** [comment]
That's correct because two images are specified for this post - https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/v1/data/blog/introducing-tailwind-nextjs-starter-blog.mdx

I don't see any duplicates so that should be fine. This post should have 1 sharing image - https://tailwind-nextjs-starter-blog-l15iqhdbd-timlrx.vercel.app/blog/new-features-in-v1

**Comment by rsipakov** [comment]
Hi @timlrx! 

When I copy-paste a [post link](https://www.timlrx.com/blog/growth-hacking-github-how-to-get-github-stars), I see the post with one image (3). When I try to share the post link to iMessage on my iPhone, I see images 1 (the main social banner) and 2 (the social banner from the blog post). This does not occur when I share the post link through other social networks (Facebook, Twitter, etc.) on my iPhone.

When I do the same tasks with another post link (https://tailwind-nextjs-starter-blog-l15iqhdbd-timlrx.vercel.app/blog/new-features-in-v1), I see only one image (4) when I do copy-paste and no image when I share to iMessage on iPhone (5 and 6).

<img width="820" alt="Screen Shot 2021-07-08 at 1 39 54 PM" src="https://user-images.githubusercontent.com/34224178/124967790-d1cec200-dff2-11eb-9546-7a052f58e703.png">

<img width="809" alt="Screen Shot 2021-07-08 at 1 48 43 PM" src="https://user-images.githubusercontent.com/34224178/124968657-ca5be880-dff3-11eb-8087-8b573a6b5de4.png">

**Comment by timlrx** [comment]
Note that https://tailwind-nextjs-starter-blog-l15iqhdbd-timlrx.vercel.app is the v1 version of the site. https://tailwind-nextjs-starter-blog.vercel.app and https://timlrx.com is an older version. 

The older version has an error that re-injects the main banner as an image instead of just using the one specified in the blog. This is fixed in the v1 branch. It is still possible to add multiple images if you include them as a list of images in the frontmatter of a post but now that can be controlled by a user.

Images 4 vs 5,6 are from different sources. 

If you want to report an error please based it on the newer v1 branch, thanks.

**Comment by rsipakov** [comment]
Got it. Thank you very much for the explanation!
