### ISSUE TITLE
Add support for comments via giscus

### ISSUE THREAD

**Issue by laymonage** [timlrx/tailwind-nextjs-starter-blog#111]
Hi there,

Thanks for the template, it looks really good!

I've got a suggestion, have you thought about adding support for comments? If not, I'm currently building [giscus](https://giscus.app), a comments system powered by GitHub Discussions. If you'd accept a PR, I could look into adding giscus integration as an optional feature to this template.

**Comment by timlrx** [comment]
Nice work on giscus! It's like utterances but uses discussions instead of issues?  Happy to accept a PR on this. Shall we implement it like in the [nobelium](https://github.com/craigary/nobelium) template? This would mean adding a config in `data/siteMetadata.js` with a [comment config field](https://github.com/craigary/nobelium/blob/main/blog.config.js#L37) and we can have a similar [comments component](https://github.com/craigary/nobelium/blob/7767a401f3868d66137f7f4cf1a38458c47450c5/components/Comments.js)

**Comment by Music47ell** [comment]
I'm working on this right now. I should have a PR ready soon.

**Comment by Music47ell** [comment]
A PR is ready that add support for giscus, utterances, disqus

https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/115
