### ISSUE TITLE
timlrx.com (Demo blog 2) shows XML

### ISSUE THREAD

**Issue by akuzni2** [timlrx/tailwind-nextjs-starter-blog#16]
Looks like there may be an issue with with timlrx.com 
![image](https://user-images.githubusercontent.com/25558903/113709775-854cb100-96a8-11eb-973c-a2925a8f33e3.png)

**Comment by timlrx** [comment]
Thanks for bringing it to my attention! It works fine locally. Have raised a ticket with vercel and hope they come back with an answer soon.

**Comment by timlrx** [comment]
Vercel support says that it is due to the way `index.xml` is injected into the system during the build which confused some of their builders and their engineers are still looking for ways to get around it. They suggested adding a manual rewrite rule to map / to /index. 

Here's the related PR and patch: https://github.com/timlrx/timlrx.com/pull/17

I won't be updating the template since it seems to be unaffected but if someone else encounters the error, hope this suggestion comes in useful.

**Comment by DoctorDerek** [comment]
Interesting 🧐
