### ISSUE TITLE
Allow JSX Support for Syntax Highlighting

### ISSUE THREAD

**Issue by mattfwood** [timlrx/tailwind-nextjs-starter-blog#173]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/22530815/128645460-31716802-95b5-410a-856a-8b711b10363c.png)

Currently, using JSX (```jsx) in MDX is not showing any syntax highlighting, and using ```js doesn't highlight JSX in the expected way.

I've looked into [Remark Prism Plus](https://github.com/timlrx/rehype-prism-plus) and there doesn't seem to be a clear way to add an additional language because `mdx.js` is using mdx-bundler, which is using XDM, which takes an array of `rehypePlugins`.

It looks like the underlying issue is that [refractor](https://github.com/wooorm/refractor) does not currently support JSX, but I was wondering if you had run into this or if I could possibly look into alternatives.

Since this is a blog built with JSX, it's likely the syntax highlighting for JSX would be a common use case.

**Additional context**
Just wanted to say, this is a really great starter and thanks for your hard work here!

And I'm definitely open to working on this myself, I've just hit a bit of a wall after trying a few things for a couple of hours.

**Comment by timlrx** [comment]
Sorry for making you chase down the prism-refractor rabbit hole. It's a small error on my part. Fixed in the latest pull request or you can just update the rehype-prism-plus package to v0.0.4. I changed it to use refractor/lib/all.js instead of the default export refractor/lib/common.js so all 258 languages including JSX are now supported.

Demo:
![image](https://user-images.githubusercontent.com/28362229/128657676-ad3454c4-807a-47c9-9eae-4f4ec00deb2e.png)
