### ISSUE TITLE
Markdown images are not lazyloaded

### ISSUE THREAD

**Issue by vahidtakro** [timlrx/tailwind-nextjs-starter-blog#217]
Hello,
I actually found out that after one of the recent updates, maybe `remark-img-to-jsx` , I can not see images are loading on "viewport" so all images in the page are loading at once when you open that page, no need to scroll, chrome inspect > network can also show that.
this is also happening in [this example](https://tailwind-nextjs-starter-blog.vercel.app/blog/guide-to-using-images-in-nextjs) , I don't know if it's a bug or not.

I also need to say that it's working well on localhost.
best,

**Comment by timlrx** [comment]
It is lazy loaded even in the example you referenced. 

> I can not see images are loading on "viewport"

That's what lazy loading means, it loads only as you scroll into view. You can see it from the network tab in the developer tools as well. Please ensure that your cache is set to disabled when trying it out.

Otherwise, please provide actual evidence that it does not work.

**Comment by vahidtakro** [comment]
> That's what lazy loading means, it loads only as you scroll into view. You can see it from the network tab in the developer tools as well. Please ensure that your cache is set to disabled when trying it out.

Thanks for the reply, I think it's loading twice, I just attached a recorded gif.

![GIF 9-4-2021 8-12-17 PM](https://user-images.githubusercontent.com/40500566/132100281-ab20f267-a8f0-449e-8bdf-6b9668f6dcc1.gif)

**Comment by timlrx** [comment]
Hmm strange, seems to be some regression introduced in 11.1.0. Upgrading to 11.1.2 fixes it.
