### ISSUE TITLE
Flash of Unstyled Text

### ISSUE THREAD

**Issue by nguyenyou** [timlrx/tailwind-nextjs-starter-blog#242]
When I repeatedly refresh the website, the layout shifts. Can we do anything about this?
Many articles are discussing this kind of issue, e.g., https://css-tricks.com/fout-foit-foft/.

https://user-images.githubusercontent.com/38455472/132949439-549b02c0-f1ef-452b-8890-79e543025868.mp4

An example of handling this issue very well: https://griko.id/ 
Repository: https://github.com/grikomsn/griko.id/tree/main/packages/v7
It also loads a google font, Manrope, and the layout stays consistent after the first, and the subsequent reloads.

**Comment by timlrx** [comment]
Both sites use the same recommended font optimization strategy of nextjs. 

From my google lighthouse test, the main demo site (https://tailwind-nextjs-starter-blog.vercel.app/) performs slightly better than the referenced site. You are probably testing my site with cache disabled? Hence the layout shifts. This happens for the referenced site as well when the fonts are swap. 

Some ways to improve it would be to switch `display=optional` instead of `display=swap`, serve the font from the same domain,  or just use a systems font. I do not automatically add the above strategies because more people would probably value ease of configuration and consistency of styling than layout shift, but feel free to configure to your preference.

**Comment by nguyenyou** [comment]
After investigation, one of my chrome extensions was causing the above problem 😓 . Oddly enough, that extension didn't affect the font loading of the referenced page.

Anyway, thank you for your response. 🙇‍♂️
