### ISSUE TITLE
XHR error in browser console

### ISSUE THREAD

**Issue by stefanradovanovic** [timlrx/tailwind-nextjs-starter-blog#271]
Firefox console is reporting XHR error on fresh install

1. Clone the repo
2. Run `npm install`
3. Run `npm run dev`
4. Open Firefox console
5. See the error

![Screenshot 2021-11-15 120336](https://user-images.githubusercontent.com/47956199/141771184-5873dbe7-c3f6-4d23-9f18-bd7e92f1e0ad.png)

 - OS: Windows 11 (WSL 2)
 - Node version: 16.13.0
 - Npm version: 8.1.3

- Device: Desktop
- Browser: Firefox
- Version: 94.0.1

**Comment by timlrx** [comment]
Hi, I managed to reproduce the error as well on chrome. That happens under `npm run dev` because the websocket at the server side is not initialize compared to running `npm start`. As a temporary workaround, if you intend to use `npm run dev`, you can remove this line of code: https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/pages/_app.js#L19

**Comment by stefanradovanovic** [comment]
Amazing, thanks!
