### ISSUE TITLE
TypeError: allRules.flat is not a function

### ISSUE THREAD

**Issue by joey00072** [timlrx/tailwind-nextjs-starter-blog#30]
TypeError: allRules.flat is not a function

I am getting this error when I try to run it on codesandbox
![aaaure](https://user-images.githubusercontent.com/35176826/115228130-025b3a00-a12f-11eb-9bb1-4d61d93e8966.PNG)

**Comment by timlrx** [comment]
Could you attach the sandbox?

**Comment by joey00072** [comment]
https://codesandbox.io/s/cocky-tree-nhhlz

**Comment by timlrx** [comment]
Codesandbox uses node 10 by default while tailwindcss requires node >=12. See this stackoverflow post for more info: https://stackoverflow.com/questions/65565095/cant-build-tailwind-css

Otherwise using node 14 in the sandbox works: https://codesandbox.io/s/silent-snowflake-5q40r?file=/sandbox.config.json

**Comment by joey00072** [comment]
Is logo allow to reuse?

**Comment by timlrx** [comment]
Yes!
