### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /node_modules/unist-util-visit/index.js

### ISSUE THREAD

**Issue by rsipakov** [timlrx/tailwind-nextjs-starter-blog#32]
**Describe the Bug**

When package.json updated to the latest version the console prints:

`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /node_modules/unist-util-visit/index.js`

**What version are you using?**

```
next": "10.1.3
unist-util-visit": "3.0.0

npm 7.10.0
```

**Comment by rsipakov** [comment]
When the `unist-util-visit": "3.0.0` downgraded to the version 2.0.3 this error disappears

**Comment by timlrx** [comment]
Hence the package specifies 2.0.3. v3 states that it is ESM only. Probably does not work with [this line](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/7a07996e3adae8050710ce7a988546cc1be103f1/lib/img-to-jsx.js#L1)

**Comment by rsipakov** [comment]
@timlrx Thank you for your quick reply. Replacing 'require'  with 'import' does not work in this case. Could you share any useful information related to this matter? Thank you!

**Comment by DoctorDerek** [comment]
Not that this issue is worth reopening per se, but fixing that line doesn't work.

Specifically I replaced it with `import {visit} from "unist-util-visit"` in `img-to-jsx.tsx` and `mdx.tsx` with `unist-util-visit@3.1.0`.

I haven't been able to track down & fix the error when using `unist-util-visit@latest` (`3.1.0`), though I suspect the error comes from the following:
```
      remarkPlugins: [
        require("remark-slug"),
        require("remark-autolink-headings"),
        require("remark-code-titles"),
        require("remark-math"),
        imgToJsx,
      ],
```
i.e. the `imgToJsx` line in `mdx.js`.

I haven't been able to get it to work at all after 2 hours of debugging in my TypeScript conversion of this project, which tells me either this `imgToJsx` file is way broken or that dependency is especially picky.

**Comment by DoctorDerek** [comment]
FWIW I got the `mdx.tsx` file to compile (sans `imgToJsx.tsx`) but only by rolling back "unist-util-visit" to the recommended `2.0.3`, but I couldn't get `imgToJsx.tsx` to work in either version.

The TypeScript error in both versions of `imgToJsx.tsx` is that no overload matches the call.

**Comment by OhYello** [comment]
I’m getting the same typescript error, did you ever find a fix?
