### ISSUE TITLE
Tags should be formatted in the way they are specified

### ISSUE THREAD

**Issue by AlexanderZeilmann** [timlrx/tailwind-nextjs-starter-blog#356]
**Is your feature request related to a problem? Please describe.**
Currently the template formats the tags differently to the way I write them.

Examples:

1. I have the tag `LaTeX`, but the tag can be found at `/tags/latex` (not `/tags/LaTeX`) and the headline says `Latex` (not `LaTeX`).
2. I have the tag `cost-efficiency analysis`. It can be found at `tags/cost-efficiency-analysis` (which is fine), but the heading says `Cost-efficiency-analysis` (first letter upper case and space replaced by a dash).

**Describe the solution you'd like**
The tag should be formatted everywhere, i.e., on the pages `/blog`,  `/blog/the-post-with-the-tag`,  `/tags`, `/tags/the-tag`,  in the exact form as it was specified.

**Describe alternatives you've considered**
I can fix this for my blogs but I thought others might like the change as well.
So I'm opening a feature request for a discussion :)

**Comment by timlrx** [comment]
There are a few parts of the blog that refer to specific tags. E.g. "the tag" gets rendered in:
1) The URL path - `/tags/the-tag`
2) The tag component itself - `THE-TAG`
3) The tag header - `The-tag` 

The URL path has to be specially formatted e.g. by removing whitespace and special characters - we use `github-slugger` for that. 

My approach, was to then make 2 and 3 follow the URL path with some styling changes e.g. all caps for the tag component and capitalizing the first letter of the first word for 3, just because I think that makes it look better 😄. I find white spaces in the tag to look pretty odd as well and might be mistaken as a different tag. A side benefit is that it combines tags that are likely to be similar e.g. `Cost-efficiency` and `cost efficiency` and `Cost Efficiency`.

I can see the rationale for keeping 2 and 3 to follow the way they are specified especially for something like `LaTeX`, but that seems more of an edge case scenario and I believe most people would prefer the current defaults.

Happy to hear other thoughts on this issue.

**Comment by timlrx** [comment]
Related Hugo discussion - https://discourse.gohugo.io/t/would-be-great-if-frontmatter-variables-didnt-have-to-be-all-lowercased/1608

At least with our situation, you can easily change it to suit your own preferences (as you mentioned) instead of having to make a change to the entire framework.

**Comment by AlexanderZeilmann** [comment]
I implemented this for my website. I'm happy to write a short description what files need to be changed if someone is interested. Closing.
