### ISSUE TITLE
How do I get rid of the styles in tailwind config and start styling from scratch?

### ISSUE THREAD

**Issue by lindamacdonald** [timlrx/tailwind-nextjs-starter-blog#364]
Hey there guys :) phenomenal blog starter! this isnt really a bug but would like to start styling the blog from scratch. I tried taking away the custom styling/ in the tailwind config, but as you might imagine ran into a lot of errors doing that. could you please let me know how I get rid of the custom styles?

**Comment by timlrx** [comment]
Thanks! I did not make too many changes to the default tailwind theme other than creating a [primary colors field](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/tailwind.config.js#L22). I don't recommend deleting that field but feel free to change to your own color palette. 

The `typography` one is the most involved as there are quite a bit of changes over there. I think the best way to customize it is to just edit the current config, rather than starting from scratch.  You can also [edit the prose element](https://tailwindcss.com/docs/typography-plugin#element-modifiers) directly. It's a new feature in tailwind 3.0 but I am on the fence between just using the defaults and moving the styling over on the prose elements themselves in the next update.

**Comment by lindamacdonald** [comment]
Thanks a mil for getting back to me on this 🙂 will Just edit the styles in the config
