### ISSUE TITLE
Google Analytics is not working/reporting

### ISSUE THREAD

**Issue by bozzmob** [timlrx/tailwind-nextjs-starter-blog#390]
**Describe the bug**
I am using the correct GA tag, but, the website doesn't seem to be reporting data in the last 24hours (since the new website's deployment)
I was earlier on Gatsbyjs and the same GA tag was working fine.

**To Reproduce**
1. Setup GA tag in siteMetadata
2. Observe the metrics on Google Analytics Dashboard

**Expected behavior**
Google Analytics should report latest analytics

**Screenshots**
![image](https://user-images.githubusercontent.com/1252941/154033966-db9748a8-5141-462a-929d-3bc4f8003578.png)

**System Info (if dev / build issue):**
 - OS: Windows11
 - Node version: v16.13.1
 - Npm version: 8.4.1

**Comment by llovvoll** [comment]
Hi bozzmob,

Please make sure you have Google Analytics sources added to Content Security Policy
https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/5f59018fa3a98ab8409f1d0b57d4808707463d0f/next.config.js#L5-L15

**Comment by bozzmob** [comment]
Thank you so much! It worked.

**Comment by interglobalmedia** [comment]
Hi,

I had a similar issue. I finally got Google Analytics to work, but then Giscus stopped working. I don't think the two work together. If I am wrong, please let me know, because I had the worst time with getting GA going. I think I might have to trash it altogether. But then the challenge will be: what will replace it? Any feedback would be very much appreciated. Thanks!

**Comment by interglobalmedia** [comment]
Hi,

I just deployed my changes with all reference to Google Analytics removed, and low and behold, Giscus worked again. Just thought I would share in case if anyone else was was banging their heads against the wall because of (big) issues with Google Analytics. And in this case, especially with Giscus. They don't play nicely together. But then Google Analytics does not play nicely with anyone!

**Comment by timlrx** [comment]
@interglobalmedia Thanks for updating. Hmm... will have to take a look in more detail. With so many external integrations included, it is a little difficulty to test that they all work fine with one another. Just to confirm you are using the GA and Giscus code from the main branch in this repository?

**Comment by interglobalmedia** [comment]
Well I cloned the repository. Yes.And I even checked the status of Giscus via the app when I did have Google Analystics running, and it had bumped me off. Then, when I removed Analytics, Giscus was up and running again. I think I did read somewhere that it does not work with Google Analytics. I think it's a privacy thing. But that's ok. They are becoming more and more difficult to work with when it comes to some of their products. I just have to find an alternative!

I did have to create a hack in the next.config file in order to get it to work. Because out of the box, when you have Giscus enabled, you can't get Google Analytics going. Chrome does not allow it, and neither does Safari or Firefox. A script src self error is thrown. Then when I added the hack in next.config.js, GA worked, and Giscus was disabled. Just FYI. I didn't want to lose the Giscus functionality, so I turned off Analytics. I am sure I am not the first to have such (or similar) experience.

**Comment by interglobalmedia** [comment]
Hi,

I am back again. I tried using plausible with and without the script that I was told to use by plausible. With script, I get the same error. Chrome does not allow the script to be loaded. Same with the other browsers. Because of the CSP.

Then, I tried to add GA again only using the starter blog config. The problem with that (now I recall why I added scripts and hacks in the first place) is that it only records the home page. So one cannot avoid adding scripts to _document.js. And then one adds code to _app.js so that changes in the route (switching from one page to another) is recorded so that not only the home page is recorded. There is no value in that. So that essentially is the issue that anyone trying to add some kind of analytics is going to encounter. I come from GatsbyJS and we had to add a script there too. Of course we had plugins for that that took care of the heavy lifting.

**Comment by interglobalmedia** [comment]
Hi,

I finally got plausible analytics to work with Giscus. So far so good. But it involves more than just adding the plausible domain in siteMetadata.js. When I simply did that, I got the CSP error. However, I found that there is a nice little next.js plugin called next-plausible, and when I added that and followed the instructions for adding it to my code, and THEN also adding plausible.io to script src along with giscus, the error went away, and plausible also works. And this plugin makes it possible to track all page views. Not just the home page. I will be writing a post about it, in case if anyone is interested in the process. It will save a lot of time and headache. The only thing is, that there is a 30 day trial and then it is 9 a month. There is no API key as far as I currently know (I will find out), and to me it is worth the avoidance of headaches!
