### ISSUE TITLE
Build step hangs at "Checking validity of types .."

### ISSUE THREAD

**Issue by darbio** [timlrx/tailwind-nextjs-starter-blog#407]
**Describe the bug**
When I run `yarn build` (or `npm run build`) on a newly cloned repository, the build process hangs at `info - Checking validity of types ..`. This stops me from deploying the solution to Vercel or any other host.

**To Reproduce**
1. `npx degit timlrx/tailwind-nextjs-starter-blog#typescript`
2. `yarn install`
3. `yarn build`

**Expected behavior**
The site should build without hanging.

**Terminal output**
```
darbio@192-168-1-110 test % npx degit timlrx/tailwind-nextjs-starter-blog#typescript
> cloned timlrx/tailwind-nextjs-starter-blog#typescript
darbio@192-168-1-110 test % yarn install
yarn install v1.22.17
warning ../../../package.json: No license field
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
info There appears to be trouble with your network connection. Retrying...
warning @mailchimp/mailchimp_marketing > superagent@3.8.1: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
warning @mailchimp/mailchimp_marketing > superagent > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
$ husky install
husky - not a Git repository, skipping hooks installation
✨  Done in 199.79s.
darbio@192-168-1-110 test % yarn build
yarn run v1.22.17
warning ../../../package.json: No license field
$ next build && node ./scripts/generate-sitemap
info  - Checking validity of types ..
```

**Comment by oliverbutler** [comment]
Same here, replicated with a fresh install.

**Comment by TszHong0411** [comment]
Try using npm

**Comment by aozaki-kuro** [comment]
I tested and found `pnpm` met the same problem, `npm` can run flawlessly.
But I would be happy to see support for `pnpm` + Typescript, it saves time and storage.

**Comment by aozaki-kuro** [comment]
Update: `pnpm` seemed to be working fine after updated to 6.32.x
TypeScript check no longer hangs

**Comment by talatkuyuk** [comment]
I have created a blog application with next-mdx-remote. It (would) works fine, but...

Just, I have utilized a function from this repository, namely `remark-code-title.ts` file which is the exact same as https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/lib/remark-code-title.js. I needed to change the file extension as `ts` since I am working typescript environment.

When I import this file as a Remark plugin in my application in local, build step hangs at "Checking validity of types in my local, and even in the Vercel build.

I had made many changes in my application, when it hanged, It was really dificult to find the bug, then I found the problem is remark-code-title.ts file.

**Comment by talatkuyuk** [comment]
What I did to overcome the problem that I depicted above:
1. Uninstall `nodejs` completely (I had installed it via homebrew before)
2. Install `nodejs` v16.14.2 via nvm
3. delete `node_modules` and `package-lock.json`
4. add typescript to package.json as devDependencies without `^`
5. I mean `"typescript": "4.6.3"`
6. `npm install` in order to install all packages again
7. Now it is okey.  I use `remark-code-title.js` file as a remark plugin. I don't see any hang issue in my local and in vercel.
