### ISSUE TITLE
How can we update our cloned project to the latest version of this source repository?

### ISSUE THREAD

**Issue by ImBIOS** [timlrx/tailwind-nextjs-starter-blog#454]
It is will be very nice if we can keep up with the latest version of this repository on our blog. So, we do not miss the new feature.

**Comment by aloisdg** [comment]
fork and sync is not enough? what do you expect exactly?

**Comment by AlexanderZeilmann** [comment]
Once you have modified the template a bit, keeping track of the changes with fork and sync becomes a bit cumbersome. This is because you also have to consider changes for components you don't care about. Also merging becomes more and more complicated the more you modify the template.

An - in my opinion better - approach would be to split the template into a collection of packages that can be included, updated or forked all independent of each other. I detailed the idea a bit more in https://github.com/timlrx/tailwind-nextjs-starter-blog/discussions/275#discussioncomment-2227502.

**Comment by timlrx** [comment]
Yes, that's what v2 is shaping up to be - a collection of packages that you can install via npm with various convenient CLI commands that you can use to bootstrap a content heavy site. Sorry, it's taking a while...

I agree that it is tedious to update to upstream changes in the repo - I don't even do it on the blogs that I run.

**Comment by ImBIOS** [comment]
Is there anyway we can help to develop the v2 @timlrx ? I would like to help, I really love the idea of this project.

**Comment by timlrx** [comment]
Let me try to get the new version out and it will be easier to contribute from there. Thanks for your interest!

**Comment by reubence** [comment]
hey @timlrx, when can we expect v2 to be available? 

I'm a tourist here who was about to fork this repo but if v2 launch is around the corner I might as well wait.

**Comment by timlrx** [comment]
Hi @reubence, it's around the corner - end of the week. But, it will be an alpha release so expect breaking changes :)

**Comment by timlrx** [comment]
If anyone is tracking this issue, I fixed a bunch of issues related to packaging and the new version should be relatively stable now, so you can just use the https://github.com/timlrx/pliny packages directly.

**Comment by ImBIOS** [comment]
Great! 😁🥳
