### ISSUE TITLE
Rss isn't modified automatically when a non-draft post is added

### ISSUE THREAD

**Issue by w9w** [timlrx/tailwind-nextjs-starter-blog#490]
Hi, I noticed that the RSS file (/public/feed.xml) isn't modified automatically when a non-draft blog post is added and there's no ability to "quickly manually" supplement it using a script as with generate-sitemap.js. The only option is to manually add blog posts' details into the RSS file.

I don't know whether it's a bug or something intended.

Best regards,
Max.

**Comment by AlexanderZeilmann** [comment]
There is the generateRSS function
https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/f6ac722192db743a1fcc91b0f44daa2c69ef2ef8/lib/generate-rss.js#L17-L31
which should be called
https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/004ac216bb3c8c1a1eaca18b2c9047395b5afbbd/pages/blog/%5B...slug%5D.js#L34-L38)
once you visit a blog post in your browser.

**Comment by w9w** [comment]
It works now but I didn't think RSS is re-generated only upon viewing arbitrary blog posts. Shouldn't RSS automatically re-generate (maybe a cron-ish job that runs every n mins) when a new post is added or a post is deleted without a need to view any post?

Best regards,
Max.

**Comment by timlrx** [comment]
Have you tried running `npm run build`? It should generate/re-generate the RSS file. In development, it is possible that the rss feed is not updated since it runs only run `getStaticProps` is triggered - https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/pages/blog/%5B...slug%5D.js#L36-L37. 

The new version makes it more explicit that the RSS feed is only generated at build time - https://github.com/timlrx/pliny/blob/main/starter-blog/package.json#L11

**Comment by w9w** [comment]
Thank you, Timothy, I'll see how it works in production. For now, I'm only on the development stage and can't check whether posts are auto-pulled to the RSS.

Best regards,
Max.
