### ISSUE TITLE
Tailwind JIT mode not updating styles

### ISSUE THREAD

**Issue by timlrx** [timlrx/tailwind-nextjs-starter-blog#54]
## Problem

Sometimes the tailwind jit engine breaks in dev mode and new styles added is not reflected in the application. See related issue in: https://github.com/tailwindlabs/tailwindcss/issues/4081

## Possible solutions

1) As a temporary patch, try modifying the tailwind config file or deleting the `.next` folder and restart the dev server
2) If you are looking for a more permanent fix, downgrading to webpack v4 supposedly helps. In `next.config.js`:
```
future: {
    webpack5: false,
},
```
3) Another fix would be to opt-out of jit mode, by deleting this [line](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/tailwind.config.js#L5) in `tailwind.config.js`

We will update to the newest version of tailwind css when the problem is fixed, but otherwise, there are no further plans to update the template for now.

**Comment by DoctorDerek** [comment]
To clarify, none of those fixes worked for me, but removing the line `mode:
"jit"` from `tailwind.config.js` then saving and adding it back does seem
to work fine, without needing to restart the dev server.

Downgrading to webpack 4 reduces the frequency that JIT stops working but
doesn't eliminate it.

The issue basically isn't being tracked over in TailwindCSS because no one
can reliably reproduce it, though it seems to be affecting everyone using
Next, so it does get re-reported every few days.

Thanks for opening the issue to clarify Tim

**Comment by timlrx** [comment]
Should be fixed in the recent upgrade - https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/88
