### ISSUE TITLE
Deployement: Help Needed Deploying to Cpanel Hosting

### ISSUE THREAD

**Issue by fffilps** [timlrx/tailwind-nextjs-starter-blog#586]
Hello all, I've built out an entire site using this template but have issues deploying it on my own hosting. I use cpanel. Has anyone ever deployed a blog from this template using cpanel? 

If so could you help me. I've used this guideline HERE[How to deploy a next.js on cpanel](https://medium.com/@geevadon/how-to-deploy-a-next-js-app-on-cpanel-efficiently-c00c5eb860de) , and it works on other next.js apps but not this one. 

Thank you all. 

PS. I want to make a blog to share with people my journey and resources used to learn web development, 3D Animations, and Photography.

**Comment by stevenrugg** [comment]
You can deploy using Vercel or Netlify. In order to delpyusing cpanel you would have to get to a command prompt of the server you're using and install Nodejs, nextjs, and the other dependencies in the package.json. Once you have Nodejs installed you can run `npm install`. In the command prompt you would have to also run `npm build` and then `npm next install --legacy-peer-deps` in order to sucessfully deploy. Vervel makes it SOOO much easier.

**Comment by timlrx** [comment]
I would recommend just using vercel or netlify for a small blog as well. Saves a lot of hassle and next 13 does not play well with a custom server setup. Otherwise, deployment issues is a little out of scope for this project.
