### ISSUE TITLE
Support for remark-embedder

### ISSUE THREAD

**Issue by sjwaight** [timlrx/tailwind-nextjs-starter-blog#618]
**Is your feature request related to a problem? Please describe.**

When migrating from another platform which support embeds (Wordpress) I was surprised by the lack of embed support out-of-the-box. I'm not a JavaScript developer and have spent a few hours trying to noodle my way through adding [remark-embedder](https://github.com/remark-embedder/core) and [transformer-oembed](https://github.com/remark-embedder/transformer-oembed) to no avail.

**Describe the solution you'd like**
It would be fantastic if these were included in the source already, even if commented out.

**Describe alternatives you've considered**
I've tried hacking away at it myself... but haven't succeeded.

**Additional context**
This is a great project and I'm pleased I found it!

**Comment by timlrx** [comment]
No plans to add it currently, but if it gets a lot of upvotes - maybe we can consider.

**Comment by lucavallin** [comment]
@timlrx I upvote this one. I'd like to have something like they do on Hashnode with `%[https://github.com/lucavallin/first-issue]` which renders to:

<img width="959" alt="image" src="https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/14332663/2e337573-64bd-4e77-8ff6-2fc25fe549f1">

:)

**Comment by timlrx** [comment]
@sjwaight @lucavallin new package is out - Remark Webembed ([npm]( https://www.npmjs.com/package/remark-webembed), [github](https://github.com/timlrx/remark-webembed))!

I decided to go with markdown directives instead of introducing a new syntax. To embed a youtube video, you can just do this:

```md
# Hello World
::embed[https://www.youtube.com/watch?v=32I0Qso4sDg]
```

Compared to `remark-embedder`, you do not need to write custom code to transform the nodes or insert HTML. The plugin handles it and creates a wrapper div to make the iframe responsive - though let me know if you encounter any edge cases. The plugin runs on the server and browser (though you might encounter CORS issues, depending on the oembed provider API).

You would need to add `remark-directive` before using this plugin. It supports all oembed and custom components (currently only Github Gist but I would probably try to port all providers from Hashnode over the next few days).

**Comment by sjwaight** [comment]
I am guessing this is only in the new release?

**Comment by timlrx** [comment]
> I am guessing this is only in the new release?

Nope, it is a generic remark package and should work with `mdx-next-remote`, `mdx-bundler`, `contentlayer` etc. Just add `remark-directive` and the new plugin (`remark-webembed`) to the list of `remarkPlugins`
