### ISSUE TITLE
Feature request: Chart 

### ISSUE THREAD

**Issue by bentondecusin** [timlrx/tailwind-nextjs-starter-blog#698]
**Is your feature request related to a problem? Please describe.**
Hey Tim! I love your template. I'm using your template to write articles on mathematical finance and I'm experimenting with adding interactive charts to the blog pages. 

**Describe the solution you'd like**
- **[chartjs](https://www.chartjs.org/)** at MDXComponents level
I've tried importing `Chart from 'react-chartjs-2'` as one of the `MDXComponents`. The problem is that `Chart` uses `useEffect` which makes it a client component, but MDXComponents is a server component. Afaik using `useEffect` in a server component is a no-no in next.js

- **chartjs** at contentlayer level
I've also tried adding [remark-mdx-chartjs](https://github.com/pangelani/remark-mdx-chartjs) as a plugin in contentlayer.config.ts. The idea is to convert a code block in chartjs (e.g. ` ``` chartjs ... ``` `) into a `<Chart/>` component. But somehow it's still rendered as a code block

- **plotly**
I've also considered using [plotly](https://plotly.com/javascript/) but it is not quite friendly to MDX.
**Additional context**

**Comment by timlrx** [comment]
I don't plan on supporting any library in particular, but you can check out a similar discussion over here on how to achieve it: https://github.com/timlrx/tailwind-nextjs-starter-blog/discussions/691

The most flexible way would be to export a chart component with the `useClient` directive and you should be able to use throughout your mdx files. Maybe I will add an example in the FAQ section since this is the 2nd time that such a request was brought up in the week.

**Comment by bentondecusin** [comment]
This helps. Thanks!

**Comment by timlrx** [comment]
Added a section in the readme for those that might be interested in implementing this: https://github.com/timlrx/tailwind-nextjs-starter-blog#how-can-i-add-a-custom-mdx-component
