### ISSUE TITLE
Make front matter type-safe

### ISSUE THREAD

**Issue by MartinMuzatko** [timlrx/tailwind-nextjs-starter-blog#732]
**Is your feature request related to a problem? Please describe.**
I'd love to know what kind of authors, layouts are valid and available at the time of writing the blogpost.
The error handling with wrong inputs (wrong layout) are cryptic at best, unfortunately.

**Describe the solution you'd like**
It could be achieved by exporting a JavaScript object instead and to use type annotations.
I know this means more boilerplate, but I'd be ready to do that, to not have all of my authors need to look up my contentlayer definitions.

**Describe alternatives you've considered**
I cannot really think of alternatives. Front-matter is not really good with types.
I could think of a possibility to have a vscode plugin recognize front-matter and link it to contentlayer, but doesn't sound really intuitive or easy to setup.
Export object with type would be more straightforward.

**Additional context**
using v2.0.2

**Comment by timlrx** [comment]
If you mean using the frontmatter properties of the blog posts, all of those is made available by contentlayer. It also verifies at build time whether anything is incorrectly specified and alerts you to it.

The only way of the type hinting to work while writing the post is for a vscode extension to be created since it needs to run external to the process. The type objects are already exported via contentlayer but I don't think there's a way to tell the markdown file that you want to type the frontmatter in a certain way.
