### ISSUE TITLE
Add blog series support

### ISSUE THREAD

**Issue by mr-loop-1** [timlrx/tailwind-nextjs-starter-blog#792]
**Is your feature request related to a problem? Please describe.**
I was thinking of adding a blog series feature which basically is clubbing multiple blogs under one topic or title. For example the series feature on [dev.to](https://dev.to/kallmanation/dev-to-writing-making-a-series-3h79)

**Describe the solution you'd like**
I would actually like to retain and reuse the current functionality only. 
- The series can replace the current previous post, next post feature resulting in previous in series, next in series
- Being part of a series is optional for a blog, using an extra series id argument in mdxx (figuring out where to initialise a series - in blog or in json like tags).
- The tags already have a dedicated page. So instead of same tags repeating in the sidebar on blogs page, we could have smaller sidebar of 5-6 _top_ tags and then another sidebar below it that lists 4-5 _top_ series.
- We can add a series route to list all blogs in the series, but I think a dedicated series page like tags page is not needed.
 
I can start working on this when I am assigned. Already have a high and low level understanding of what needs to be changed.

**Comment by timlrx** [comment]
Hmm, I think a cleaner solution might be to consider all mdx within a subfolder route to be part of a series and replace the existing navigation buttons / include an additional navigation component to link the series. 

Not the hardest to implement, but I am wary of changing the existing behaviour as well. On the UI side, the list view should also reflect the series. All in all, there's quite a bit of opinionated changes. If you have implemented it on your blog, I would be happy to link it in the examples, but otherwise I don't think the additional feature is necessary.

**Comment by mr-loop-1** [comment]
Well, you solved the only part I was not sure about which was how to make a blog opt-in a series, and its to drop it into a sub folder, with sub folder's name becoming the title of the series

**Comment by PxlSyl** [comment]
> Well, you solved the only part I was not sure about which was how to make a blog opt-in a series, and its to drop it into a sub folder, with sub folder's name becoming the title of the series

Hi! I don't think what I did cover all the features you're looking for (and I still want to have something quite similar to the original repository) but if you want to have a look, I've added series support in the i18n version 

Example from my demo here, with series box at the top of the article : https://tailwind-nextjs-starter-blog-i18n.vercel.app/fr/blog/articles/internationalisation-v2
