### ISSUE TITLE
How do we style KBar?

### ISSUE THREAD

**Issue by juskek** [timlrx/tailwind-nextjs-starter-blog#811]
Hey there, great template!

Is it possible to style KBar? I've removed dark mode from the site but KBar is still in dark mode

<img width="642" alt="image" src="https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/57725347/2602e317-984a-485c-9a6a-907f81e0cf69">

**Comment by juskek** [comment]
Had to set   darkMode: 'false' in tailwind.config.js

Would be cool if there was a way to style the KBar directly though

**Comment by PxlSyl** [comment]
> Had to set darkMode: 'false' in tailwind.config.js
> 
> Would be cool if there was a way to style the KBar directly though

It' possible, but you'll need to copy paste the kbar components from Pliny in your app, and reorganize imports. I did it for  my unofficial i18n version (in my case, to manage translations)

**Comment by timlrx** [comment]
Hi @juskek, it follows the tailwind dark mode setting of the site. Rather than modify `tailwind.config.js`, I suggest keeping the default and modifying [siteMetadata](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/main/data/siteMetadata.js#L8) - this will propagate the changes correctly (if you toggle the theme switch on the demo website, you can see that the kbar search also changes accordingly). 

For other changes and maximum flexibility, it will be easier to copy the code from [pliny](https://github.com/timlrx/pliny/blob/main/packages/pliny/src/search/KBar.tsx) and modify the tailwind styles accordingly.
