### ISSUE TITLE
#842 Issue Is the 842 error still the same?

### ISSUE THREAD

**Issue by Samdasoo1076** [timlrx/tailwind-nextjs-starter-blog#933]
[#842](https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/842)

I'm trying to use Giscus https://giscus.app/ but I've done all the necessary settings in the repository and installed it in the repository, but I'm getting an error: ```"giscus is not installed on this repository"```
works. Next.js version is 14.2.3.

## my .env.example 

NEXT_PUBLIC_GISCUS_REPO="Samdasoo1076/blog-test"
NEXT_PUBLIC_GISCUS_REPOSITORY_ID="R_kgDOMFy0gQ"
NEXT_PUBLIC_GISCUS_CATEGORY="General"
NEXT_PUBLIC_GISCUS_CATEGORY_ID="DIC_kwDOMFy0gc4Cf6GO"
NEXT_PUBLIC_UTTERANCES_REPO=
NEXT_PUBLIC_DISQUS_SHORTNAME=

**Comment by timlrx** [comment]
The current preview blog uses Next.js 14.2.3 so there should not be any issue. Please ensure that you have carried out the following steps:

> The repository is [public](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/setting-repository-visibility#making-a-repository-public), otherwise visitors will not be able to view the discussion.
The [giscus](https://github.com/apps/giscus) app is installed, otherwise visitors will not be able to comment and react.
The Discussions feature is turned on by [enabling it for your repository](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/enabling-or-disabling-github-discussions-for-a-repository).

**Comment by Samdasoo1076** [comment]
I tried all the answers you gave me before I posted the issue, but it didn't work 
Is the surest way to initialize the project?

**Comment by laymonage** [comment]
[You should put those values on Vercel](https://vercel.com/docs/projects/environment-variables) or an `.env` file, not `.env.example`. As the name suggests, `.env.example` is just an example.

**Comment by Samdasoo1076** [comment]
oh... thank you 
i Solved this problem
