### ISSUE TITLE
Blog title contain comma will cause 404

### ISSUE THREAD

**Issue by JcobCN** [timlrx/tailwind-nextjs-starter-blog#952]
**Describe the bug**
Mdx title contain comma will cause 404

**To Reproduce**

just add some comma in Mdx file title, like this:
```
---
title: sushiswap MCF v1,v2 MiniChef合约解读
date: '2023-02-28 04:19:00'
tags: ['crypto','code']
draft: false
---

...some contents.

```
between in 'v1' and 'v2', and will see this page 404.

**Expected behavior**
correctly display, not 404

**Screenshots**
![image](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/19268110/89bdde11-0cdb-4e49-8c5c-5bd1ff26455e)

**System Info (if dev / build issue):**

- Node version (please ensure you are using 18+)
- Npm version

**Browser Info (if display / formatting issue):**

- Version v2.1.0

**Additional context**
I add console.log in /app/blog/[...slug]/page.tsx function Page()
```js
sortedCoreContents.forEach((b)=>{
    if (b.slug.includes('sushi')){
    console.log(b.slug)
    console.log(b.filePath)}
  })
```
you'll see the same slug print twice. but i not familiar with js/ts.

![image](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/19268110/fe9d0f74-7ed7-41a7-a98d-6432a30eee9d)

I use `/` instead of `,` to avoid this.

**Comment by kenaqshal** [comment]
Hi @JcobCN Upon investigating, I found that the issue is not with the title in the MDX file itself, but with the file name. The dynamic route doesn't handle slugs with commas correctly. 

Solution:
To avoid this issue, **replace** commas with hyphens in the file name.

For example:
sushiswap-mcf-v1,v2-MiniChef合约解读.mdx (causes error)
sushiswap-mcf-v1-v2-MiniChef合约解读.mdx (works)

![image](https://github.com/user-attachments/assets/84df1438-f92e-4d92-9d32-fa37108f875f)

**Comment by timlrx** [comment]
yes, please avoid commas in the file name, thanks!
